### PR TITLE
Fixing columns for better viewing on GitHub

### PR DESCRIPTION
**Pull request by zubairzia0**

### CODE REVIEW

**Comment by xaur** [comment]
Hey thanks for the PR. Why does it remove all quotes?

**Comment by zubairzia0** [comment]
is there a need for the quotes?

**Comment by xaur** [comment]
Not sure, but if a cell contains a comma (Title may), it better be quoted to avoid conflicts with CSV format.

In any case, it's better to have large scale reformatting and a small fix separate changes.

**Comment by RichardRed0x** [comment]
Yes there is a need for the quotes. As @xaur alluded to they prevent characters within titles being interpreted as delimiters and making a mess of the whole file.

I also encountered formatting issues when opening the file in libreoffice and saving it. I think this is because of the locale settings of the spreadsheet editor and its defaults for saving .csv files. 

It's another problem with the csv-GitHub workflow, which I think will not be appropriate for casual row adding.

**Comment by xaur** [comment]
#21 is to settle on the format, then we can rebase and merge this PR.

**Comment by xaur** [comment]
This was fixed in https://github.com/RichardRed0x/decred-media-tracker/commit/411df04a3605ca33f785fd3d604201a29cb37915 , closing.

**Pull request closed without merging**
